version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: dbMeckano
      DB_DATABASE: Meckano
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - dbMeckano
    ports:
      - "8000:8000"
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app

  dbMeckano:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: Meckano
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - dbMeckano
    ports:
      - "8080:80"
    environment:
      PMA_HOST: dbMeckano
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mysql_data:
